# 次のプログラムを実行したときに発生する例外の方はどれでしょうか？

my_list = []
my_list.insert(3)

① IndexError
② KeyError
③ ZeroDivisionError
④ ValueError

# 正解③
